#!/bin/bash

monitor=$(xrandr -q | grep primary | awk '{print $1;}')

pgrep -x sxhkd > /dev/null || sxhkd &
~/.scripts/init-resolution
xsetroot -cursor_name left_ptr &
udiskie &
#eww daemon
playerctld daemon
dbus-launch
syncthingtray --wait &
notification-center &
picom &
emacs &
#xborders -c ~/.config/xborder/config.json &

bspc config border_radius               5
bspc config border_width                2

bspc config normal_border_color         "#000000"
bspc config active_border_color         "#1D814F"
bspc config focused_border_color        "#FFFFFF"
bspc config presel_feedback_color       "#FFFFFF"

bspc config window_gap                  8
bspc config bottom_padding              0
bspc config -m $monitor bottom_padding  54
bspc config focus_follows_pointer       true
bspc config pointer_follows_monitor     true
bspc config pointer_follows_focus       true

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true


bspc rule -a discord state=floating rectangle=1660x925+100+50
bspc rule -a BlueMail state=floating rectangle=1660x925+100+50
bspc rule -a Mailspring state=floating rectangle=1440x900+230+70
bspc rule -a Emacs state=tiled

bspc subscribe node_add | while read line
do
    windowid=$(echo "$line" | awk '{print $5}')
    title=$(xtitle $windowid)
    class=$(xdotool getwindowclassname $windowid)

    case $title in
        Ranger|Lyrics|Calendar)
            bspc node -t floating
            bspc node -z left -100 0
            bspc node -z top 0 -30
            bspc node -z right 100 0
            bspc node -z bottom 0 -15
            ;;
    esac
done
