#!/bin/sh

isHDMIConnected() { 
	local xRandr=$(xrandr -q)
	[ "$xRandr" == "${xRandr#*DP-3 con}" ] || return 0
	return 1
}

xrandr --output eDP-1 --right-of DP-3

if isHDMIConnected
then
	xrandr --output DP-3 --primary
	xrandr --output eDP-1 --mode 1920x1080
	sleep 1
    startup
else
	xrandr --output eDP-1 --primary
	xrandr --output eDP-1 --mode 1920x1080
	sleep 2
    startup2
fi
