#!/usr/bin/python3
import pyautogui
import os

minimal = True
previous = pyautogui.position()
while True:
    position = pyautogui.position()
    if position != previous and position.y > 1050 and minimal:
        os.system('killall polybar')
        os.system('bspc config -m DP-3 bottom_padding 60')
        os.system('~/.config/polybar/launch_old.sh')
        minimal = False
    elif position != previous and position.y <= 1010 and not minimal:
        os.system('killall polybar')
        os.system('bspc config -m DP-3 bottom_padding 30')
        os.system('~/.config/polybar/launch.sh')
        minimal = True
    previous = position
