#!/bin/bash

minimal=true
last_x=$(xdotool getmouselocation | awk {'print $1'} | cut -d':' -f2)
last_y=$(xdotool getmouselocation | awk {'print $2'} | cut -d':' -f2)
monitor=$(xrandr -q | grep primary | awk '{print $1;}')
while true
do
    x=$(xdotool getmouselocation | awk {'print $1'} | cut -d':' -f2)
    y=$(xdotool getmouselocation | awk {'print $2'} | cut -d':' -f2)
    if ! [[ $last_x -eq $x && $last_y -eq $y ]];
    then
        if [[ $y -gt 1070 && $minimal = true ]];
        then
            bspc config -m $monitor bottom_padding 54
            polybar-msg cmd show
            minimal=false
        elif [[ $y -lt 1010 && $minimal = false ]];
        then
            bspc config -m $monitor bottom_padding 0
            polybar-msg cmd hide
            minimal=true
        fi
        last_x=$x
        last_y=$y
    fi
done
