#!/bin/sh

bspc monitor DP-3 -f
nitrogen --restore
~/.scripts/polybarstart &
~/.scripts/mousewatch &
~/.scripts/pulseaudio-watcher | xob -s monitor &
blueman-applet & > /dev/null
discord --start-minimized & > /dev/null
