#!/bin/bash
# Selects DP-1 as primary monitor
xrandr --output "DP-1" --primary

hyprpaper &
mediapipe &
swaync &
eww daemon
discord --start-minimized --enable-features=UseOzonePlatform --ozone-platform=wayland /opt/discord/resources/app.asar & > /dev/null
waybar -c ~/.config/waybar/config &
~/.scripts/pulseaudio | wob -c ~/.config/wob/wob.ini &

hyprctl dispatch focusmonitor DP-1
emacs &
#mailspring -b &
